### ISSUE TITLE
Maven plugin: support for a "warning only" mode

### ISSUE THREAD

**Issue by Stephan202** [kordamp/pomchecker#9]
First off: thanks for providing this nice project!

Maven plugins that perform some kind of validation often provide a flag to toggle whether violations should fail the build, or are merely logged. I was wondering whether you have considered adding a similar feature for this project's Maven plugin? For examples see [this Maven profile](https://github.com/PicnicSupermarket/error-prone-support/blob/a55ed9cea9aef6ae04ed78237612aa9ca008b06a/pom.xml#L1644-L1733), where the relevant properties have names such as `failOnError`, `failOnViolation` and `failOnWarning`.

Context for this request: the requested feature would simplify PicnicSupermarket/error-prone-support#491, and allow the plugin to participate in our build's warn-but-don't-fail mode.

**Comment by aalmiray** [comment]
Thanks 😅 

I think adding a `failOnError` setting would be the way to go.

**Comment by aalmiray** [comment]
@Stephan202 FWIW I believe pomchecker does not fail build when a warning is emitted, only when there are errors.
Do you also want to suppress warnings?

**Comment by Stephan202** [comment]
> Do you also want to suppress warnings?

Good question. I'm tending to "yes", but I'm not sure that blanket suppression is most useful. For example, if we decide to fix [this](https://github.com/kordamp/pomchecker/blob/2f07c4a41db86dd618f4176afc3e40bf2bc0778b/pomchecker-core/src/main/java/org/kordamp/maven/checker/MavenCentralChecker.java#L116-L117) warning in our code, then afterwards I'd want to guard against new violations by raising its severity to an error. But I realize that this significantly expands the scope of this feature request from "add a `failOnError` flag" to "allow each check to be assigned a severity of `OFF`, `WARN` or `ERROR`, and fail if there are any `ERROR`s." :grimacing:

**Comment by aalmiray** [comment]
I see. I'm not so sure if every check should have it's own status as the whole point of this tool is to raise awareness of missing XML elements. There are however two types of elements: 
 1. required. Should trigger `ERROR` when missing. Maven Central rules will trigger when a pom is uploaded.
 2. explicitly missing but inherited. They trigger `WARN` because their value is not explicitly set. These are perhaps the ones that could have a severity assigned as their inferred value should not cause issues when Maven Central checks them.

Thus, I can add a `failOnError` flag to skip failing the build when needed, as well as check states for elements of type 2.

WDYT?

**Comment by Stephan202** [comment]
@aalmiray yes, that makes sense to me :+1:

**Comment by aalmiray** [comment]
@Stephan202 I've added `failOnError` and `failOnWarning` properties. Do let me know if additional fine grained control for `<url>`, `<repositories>`, and `<pluginRepositories>` is needed.

**Comment by Stephan202** [comment]
@aalmiray I just tested it by modifying the PR mentioned in the issue description: it works very nicely! Thanks for implementing this feature! :rocket:

**Comment by aalmiray** [comment]
Alright. I'll go ahead and release 1.8.0 this weekend.

**Comment by aalmiray** [comment]
Released in v1.8.0 -> https://github.com/kordamp/pomchecker/releases/tag/v1.8.0
